version: '3'
services:
  movie:
    image: harry3210/phonepaymovies:v1
    ports:
      - "8000:80"
    deploy:
      replicas: 4    

  train:
    image: harry3210/phonepaytrains:v1
    ports:
      - "8001:80"
    deploy:
      replicas: 4
    
  recharge:
    image: harry3210/phonepayrecharges:v1
    ports:
      - "8002:80"    
    deploy:
      replicas: 4
      
